---
title: "Sanford Competition EDA - DSU"
author: "Martin Kloster"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set-Up
```{r Libraries, include=FALSE, warning=FALSE}
library(tidyverse)
library(readr)
library(GGally)
library(tidyquant)
```

```{r Data_Import}
Sanford_ED <- read.csv("../DSU-Dataset.csv")
```

``` {r Data_Creation}
# Creates Variables: Shift, Season
Sanford_ED <- Sanford_ED %>%
  mutate(DateTime = as.POSIXct(paste(Date, sprintf("%02d:00:00", Hour),tz="America/Chicago"))) %>%
  mutate(Shift = (Hour %/% 6) + 1, .after = Hour)  %>%
  mutate(Year = year(Date), .after = Date) %>%
  mutate(Season = (month(Date) + 2) %/% 3, .after = Year)

# ========== Time Table ==========
# Calculates Elapsed Time in Dataset (Sanity Check for Time Table)
Timeframe.Start <- as.POSIXct("2018-01-01 00:00:00", tz="America/Chicago")
Timeframe.End <- as.POSIXct("2025-08-31 23:00:00", tz="America/Chicago")
Total_Days <- as.numeric(difftime(Timeframe.End, Timeframe.Start, units = "days"))
Total_Hours <- as.numeric(difftime(Timeframe.End, Timeframe.Start, units = "hours"))

# Sites, for crossing
ED_Sites <- c('A','B','C','D')

# New Central Time Table
Timetable <- data.frame(
  DateTime = seq(
    from = Timeframe.Start,
    to = Timeframe.End,
    by = "hour"))

# Sites required for proper joining
Timetable.Sites <- crossing(Site = ED_Sites, DateTime = Timetable$DateTime)

# Summarizes ED Visits for merging to Timetable
Summary.Hourly <- Sanford_ED %>%
  group_by(Site, DateTime) %>%
  summarise(Events = n(),
            Presented.Sum = sum(ED.Enc),
            Presented.Avg = mean(ED.Enc),
            Admissions.Sum = sum(ED.Enc.Admitted),
            Admissions.Avg = mean(ED.Enc.Admitted),
            .groups = "drop")

# Central timetable. Accounts for DateTimes w/ no Events.
Sanford_ED.Timetable <- left_join(Timetable.Sites,
                                  Summary.Hourly,
                                  by = join_by(Site, DateTime)) %>%
  mutate(across(where(is.numeric), ~ replace_na(.x, 0)))
  
```
## Data Filtering
  Need to check if all hours represented, if columns still correspond after table manipulation. May not be accurate or even work before check. Switched variable names to be more descriptive and clear. Will need to check later plotting for consistency.

``` {r Filtered_Data}
# ========== Events ==========
# Events by Hour
Events.Hourly <- Sanford_ED[c(1,2,5)] %>%
  group_by(Site, Date, Hour) %>%
  summarise(cases = n(), .groups = "drop") %>%
  group_by(Site, Hour) %>%
  summarise(cases.count = sum(cases),
            cases.avg = mean(cases),
            .groups = "drop")

# Events by Hour (Filtered: Oct, Nov)
Events.Hourly.Oct_Nov <- Sanford_ED[c(1,2,5)] %>%
  filter(month(Date) %in% c(10,11)) %>%
  group_by(Site, Date, Hour) %>%
  summarise(cases = n(), .groups = "drop") %>%
  group_by(Site, Hour) %>%
  summarise(cases.count = sum(cases),
            cases.avg = mean(cases),
            .groups = "drop")

# Events by Years and Hours
Events.Hourly_Years <- Sanford_ED[c(1:3,5)] %>%
  group_by(Site, Date, Year, Hour) %>%
  summarise(cases = n(), .groups = "drop") %>%
  group_by(Site, Year, Hour) %>%
  summarise(cases.count = sum(cases),
            cases.avg = mean(cases),
            .groups = "drop")

# Events by Years and Seasons
Events.Seasonal_Years <- Sanford_ED[c(1:4)] %>%
  group_by(Site, Date, Year, Season) %>%
  summarise(cases = n(), .groups = "drop") %>%
  group_by(Site, Year, Season) %>%
  summarise(cases.count = sum(cases),
            cases.avg = mean(cases),
            .groups = "drop")

# ========== Admissions ==========
# Admissions by Hour
Admissions.Hourly <- Sanford_ED %>%
  group_by(Site, Date, Hour) %>%
  summarise(Admissions = sum(ED.Enc.Admitted),.groups = "drop") %>%
  group_by(Site, Hour) %>%
  summarise(Admissions.avg = mean(Admissions), .groups = "drop")

# Admissions by Shift
Admissions.Shift <- Sanford_ED %>%
  group_by(Site, Date, Shift) %>%
  summarise(Admissions = sum(ED.Enc.Admitted),.groups = "drop") %>%
  group_by(Site, Shift) %>%
  summarise(Admissions.avg = mean(Admissions), .groups = "drop")
```

```{r Data_Plotting}
# ========== Events ==========
# Line Chart: Events by Hour (Filtered: Oct, Nov)
Events.Hourly.Oct_Nov.LC <- Events.Hourly.Oct_Nov %>%
  ggplot(aes(
    x=Hour,
    y=cases.avg,
    group = Site,
    color = Site)) +
  geom_line(linewidth = 1) +
  labs(title = "Hourly Average Visits by Site: October, November") +
  theme_bw()

# Line Chart: Events by Hour (Faceted: Years)
Events.Hourly.Facet_Years.LC <- Events.Hourly_Years %>%
  ggplot(aes(
    x=Hour,
    y=cases.count,
    group = Site,
    color = Site)) +
  geom_line(linewidth = 1) +
  facet_wrap(~Year) +
  labs(title = "Hourly Average Visits by Site: All Months") +
  theme_bw()

# Line Chart: Events by Season (Facet: Years)
Events.Seasonal.Facet_Years.LC <- Events.Seasonal_Years %>%
  ggplot(aes(
    x=Season,
    y=cases.count,
    group = Site,
    color = Site)) +
  geom_line(linewidth = 1) +
  facet_wrap(~Year) +
  labs(title = "Hourly Average Visits by Site: All Months") +
  theme_bw()

# ========== Admissions ==========
# Line Chart: ED Admissions by Hour
Admissions.Hourly.LC <- Admissions.Hourly %>%
  ggplot(aes(
    x=Hour,
    y=Admissions.avg,
    group = Site,
    color = Site)) +
  geom_line(linewidth = 1) +
  labs(title = "Avg Admissions by Hour, Site (All Months)") +
  theme_bw()

# Line Chart: ED Admissions by Shift
Admissions.Shift.LC <- Admissions.Shift %>%
  group_by(Shift) %>%
  ggplot(aes(
    x=Shift,
    y=Admissions.avg,
    group = Site,
    color = Site)) +
  geom_line(linewidth = 1) +
  labs(title = "Avg Admissions by Shift, Site (All Months)") +
  theme_bw()
```

``` {r Display}
# Events
Events.Hourly.Facet_Years.LC
Events.Hourly.Oct_Nov.LC
Events.Seasonal.Facet_Years.LC

# Number Presenting to ED

# ED Admissions
Admissions.Hourly.LC
Admissions.Shift.LC
```
